### ISSUE TITLE
Error seen in log

### ISSUE THREAD

**Issue by iceb0y** [vijos/vj4#150]
```
Apr  5 10:47:29 vj4 python3.5[385]: #033[31m[E 170405 10:47:29 web_protocol:358]#033[0m Error handling request
Apr  5 10:47:29 vj4 python3.5[385]: Traceback (most recent call last):
Apr  5 10:47:29 vj4 python3.5[385]:   File "/home/vijos/vj4/vj4/handler/base.py", line 216, in __iter__
Apr  5 10:47:29 vj4 python3.5[385]:     yield from HandlerBase.prepare(self)
Apr  5 10:47:29 vj4 python3.5[385]:   File "/home/vijos/vj4/vj4/handler/base.py", line 35, in prepare
Apr  5 10:47:29 vj4 python3.5[385]:     self.session = await self.update_session()
Apr  5 10:47:29 vj4 python3.5[385]:   File "/home/vijos/vj4/vj4/handler/base.py", line 126, in update_session
Apr  5 10:47:29 vj4 python3.5[385]:     'update_ua': self.request.headers.get('User-Agent')})
Apr  5 10:47:29 vj4 python3.5[385]:   File "/home/vijos/vj4/vj4/model/token.py", line 105, in update
Apr  5 10:47:29 vj4 python3.5[385]:     return_document=ReturnDocument.AFTER)
Apr  5 10:47:29 vj4 python3.5[385]:   File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
Apr  5 10:47:29 vj4 python3.5[385]:     yield self  # This tells Task to wait for completion.
Apr  5 10:47:29 vj4 python3.5[385]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
Apr  5 10:47:29 vj4 python3.5[385]:     future.result()
Apr  5 10:47:29 vj4 python3.5[385]:   File "/usr/lib/python3.5/asyncio/futures.py", line 266, in result
Apr  5 10:47:29 vj4 python3.5[385]:     raise CancelledError
Apr  5 10:47:29 vj4 python3.5[385]: concurrent.futures._base.CancelledError
Apr  5 10:47:29 vj4 python3.5[385]: During handling of the above exception, another exception occurred:
Apr  5 10:47:29 vj4 python3.5[385]: Traceback (most recent call last):
Apr  5 10:47:29 vj4 python3.5[385]:   File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_protocol.py", line 417, in start
Apr  5 10:47:29 vj4 python3.5[385]:     resp = yield from self._request_handler(request)
Apr  5 10:47:29 vj4 python3.5[385]:   File "/usr/local/lib/python3.5/dist-packages/aiohttp/web.py", line 289, in _handle
Apr  5 10:47:29 vj4 python3.5[385]:     resp = yield from handler(request)
Apr  5 10:47:29 vj4 python3.5[385]:   File "/home/vijos/vj4/vj4/handler/base.py", line 231, in __iter__
Apr  5 10:47:29 vj4 python3.5[385]:     self.url, self.remote_ip, (self.user and self.user['_id']) or None, repr(e))
Apr  5 10:47:29 vj4 python3.5[385]: AttributeError: 'DiscussionNodeHandler' object has no attribute 'user'#033[0m
Apr  5 10:47:29 vj4 python3.5[385]: #033[31m[E 170405 10:47:29 web_protocol:358]#033[0m Error handling request
Apr  5 10:47:29 vj4 python3.5[385]: Traceback (most recent call last):
Apr  5 10:47:29 vj4 python3.5[385]:   File "/home/vijos/vj4/vj4/handler/base.py", line 216, in __iter__
Apr  5 10:47:29 vj4 python3.5[385]:     yield from HandlerBase.prepare(self)
Apr  5 10:47:29 vj4 python3.5[385]:   File "/home/vijos/vj4/vj4/handler/base.py", line 35, in prepare
Apr  5 10:47:29 vj4 python3.5[385]:     self.session = await self.update_session()
Apr  5 10:47:29 vj4 python3.5[385]:   File "/home/vijos/vj4/vj4/handler/base.py", line 126, in update_session
Apr  5 10:47:29 vj4 python3.5[385]:     'update_ua': self.request.headers.get('User-Agent')})
Apr  5 10:47:29 vj4 python3.5[385]:   File "/home/vijos/vj4/vj4/model/token.py", line 105, in update
Apr  5 10:47:29 vj4 python3.5[385]:     return_document=ReturnDocument.AFTER)
Apr  5 10:47:29 vj4 python3.5[385]:   File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
Apr  5 10:47:29 vj4 python3.5[385]:     yield self  # This tells Task to wait for completion.
Apr  5 10:47:29 vj4 python3.5[385]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
Apr  5 10:47:29 vj4 python3.5[385]:     future.result()
Apr  5 10:47:29 vj4 python3.5[385]:   File "/usr/lib/python3.5/asyncio/futures.py", line 266, in result
Apr  5 10:47:29 vj4 python3.5[385]:     raise CancelledError
Apr  5 10:47:29 vj4 python3.5[385]: concurrent.futures._base.CancelledError
Apr  5 10:47:29 vj4 python3.5[385]: During handling of the above exception, another exception occurred:
Apr  5 10:47:29 vj4 python3.5[385]: Traceback (most recent call last):
Apr  5 10:47:29 vj4 python3.5[385]:   File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_protocol.py", line 417, in start
Apr  5 10:47:29 vj4 python3.5[385]:     resp = yield from self._request_handler(request)
Apr  5 10:47:29 vj4 python3.5[385]:   File "/usr/local/lib/python3.5/dist-packages/aiohttp/web.py", line 289, in _handle
Apr  5 10:47:29 vj4 python3.5[385]:     resp = yield from handler(request)
Apr  5 10:47:29 vj4 python3.5[385]:   File "/home/vijos/vj4/vj4/handler/base.py", line 231, in __iter__
Apr  5 10:47:29 vj4 python3.5[385]:     self.url, self.remote_ip, (self.user and self.user['_id']) or None, repr(e))
Apr  5 10:47:29 vj4 python3.5[385]: AttributeError: 'ProblemMainHandler' object has no attribute 'user'#033[0m
Apr  5 10:47:29 vj4 python3.5[385]: #033[31m[E 170405 10:47:29 web_protocol:358]#033[0m Error handling request
Apr  5 10:47:29 vj4 python3.5[385]: Traceback (most recent call last):
Apr  5 10:47:29 vj4 python3.5[385]:   File "/home/vijos/vj4/vj4/handler/base.py", line 216, in __iter__
Apr  5 10:47:29 vj4 python3.5[385]:     yield from HandlerBase.prepare(self)
Apr  5 10:47:29 vj4 python3.5[385]:   File "/home/vijos/vj4/vj4/handler/base.py", line 35, in prepare
Apr  5 10:47:29 vj4 python3.5[385]:     self.session = await self.update_session()
Apr  5 10:47:29 vj4 python3.5[385]:   File "/home/vijos/vj4/vj4/handler/base.py", line 126, in update_session
Apr  5 10:47:29 vj4 python3.5[385]:     'update_ua': self.request.headers.get('User-Agent')})
Apr  5 10:47:29 vj4 python3.5[385]:   File "/home/vijos/vj4/vj4/model/token.py", line 105, in update
Apr  5 10:47:29 vj4 python3.5[385]:     return_document=ReturnDocument.AFTER)
Apr  5 10:47:29 vj4 python3.5[385]:   File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
Apr  5 10:47:29 vj4 python3.5[385]:     yield self  # This tells Task to wait for completion.
Apr  5 10:47:29 vj4 python3.5[385]: concurrent.futures._base.CancelledError
Apr  5 10:47:29 vj4 python3.5[385]: During handling of the above exception, another exception occurred:
Apr  5 10:47:29 vj4 python3.5[385]: Traceback (most recent call last):
Apr  5 10:47:29 vj4 python3.5[385]:   File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_protocol.py", line 417, in start
Apr  5 10:47:29 vj4 python3.5[385]:     resp = yield from self._request_handler(request)
Apr  5 10:47:29 vj4 python3.5[385]:   File "/usr/local/lib/python3.5/dist-packages/aiohttp/web.py", line 289, in _handle
Apr  5 10:47:29 vj4 python3.5[385]:     resp = yield from handler(request)
Apr  5 10:47:29 vj4 python3.5[385]:   File "/home/vijos/vj4/vj4/handler/base.py", line 231, in __iter__
Apr  5 10:47:29 vj4 python3.5[385]:     self.url, self.remote_ip, (self.user and self.user['_id']) or None, repr(e))
Apr  5 10:47:29 vj4 python3.5[385]: AttributeError: 'ProblemMainHandler' object has no attribute 'user'#033[0m
```

**Comment by twd2** [comment]
Might be fixed by 711a28ef.
