### ISSUE TITLE
上传数据失败

### ISSUE THREAD

**Issue by Ruanxingzhi** [vijos/vj4#202]
Error 500 Server got itself in trouble。
如图（图片地址在`http://i4.buimg.com/588926/dcae5f59d1846d08.png`）：
![233](http://i4.buimg.com/588926/dcae5f59d1846d08.png)

部署在docker里面。实体机和docker镜像都是ubuntu 17.04。

错误报告：
```
root@012209f73f5f:~/vijos# ./star 
 * Starting database mongodb                                                     [ OK ] 
 * Starting RabbitMQ Messaging Server rabbitmq-server                                    * RabbitMQ Messaging Server already running
                                                                                 [ OK ]
[I 170511 12:00:41 tools:17] Ensuring indexes for "document".
[I 170511 12:00:41 protocol:491] Recv open ok
[I 170511 12:00:41 tools:17] Ensuring indexes for "domain".
[I 170511 12:00:41 tools:17] Ensuring indexes for "fs".
[I 170511 12:00:41 tools:17] Ensuring indexes for "message".
[I 170511 12:00:41 tools:17] Ensuring indexes for "opcount".
[I 170511 12:00:41 tools:17] Ensuring indexes for "oplog".
[I 170511 12:00:41 tools:17] Ensuring indexes for "record".
[I 170511 12:00:41 tools:17] Ensuring indexes for "system".
[I 170511 12:00:41 tools:17] Ensuring indexes for "token".
[I 170511 12:00:41 tools:17] Ensuring indexes for "user".
======== Running on http://0.0.0.0:80 ========
(Press CTRL+C to quit)
[E 170511 12:00:59 base:236] System error by /p/5914527886cf00031a50c9f6/upload 172.17.0.1 2: ValueError("Invalid boundary b'', expected b'------WebKitFormBoundarydb26q3ozJnpOmgTf'",)
[E 170511 12:00:59 web_protocol:358] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_protocol.py", line 417, in start
    resp = yield from self._request_handler(request)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web.py", line 289, in _handle
    resp = yield from handler(request)
  File "/root/vijos/vj4/handler/base.py", line 219, in __iter__
    yield from super(Handler, self).__iter__()
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_urldispatcher.py", line 657, in __iter__
    resp = yield from method()
  File "/root/vijos/vj4/handler/base.py", line 439, in wrapped
    async for part in await self.request.multipart():
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/multipart.py", line 543, in __anext__
    part = yield from self.next()
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/multipart.py", line 577, in next
    yield from self._read_boundary()
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/multipart.py", line 672, in _read_boundary
    % (chunk, self._boundary))
ValueError: Invalid boundary b'', expected b'------WebKitFormBoundarydb26q3ozJnpOmgTf'

root@012209f73f5f:~/vijos# npm --version
4.2.0
root@012209f73f5f:~/vijos# node --version
v7.10.0
root@012209f73f5f:~/vijos# python3 --version
Python 3.5.3
```

`star`是一个启动脚本，它的内容：
```
service mongodb start
service rabbitmq-server start

python3 -OO -m vj4.server --listen=http://0.0.0.0:80 --smtp-host=smtp.gmail.com  --smtp-user=ruanxingzhi@gmail.com --smtp-password=************ --url-prefix=http://127.0.0.1
```

**Comment by SkyLionel** [comment]
I have the same problem...

**Comment by iceb0y** [comment]
No problem here. What's your aiohttp version (you can `pip3 freeze` and post it here) and chrome version?

**Comment by iceb0y** [comment]
seeing same error on vijos.org

**Comment by iceb0y** [comment]
Found out removing `-OO` parameter fixes the problem.

There's either a problem in `aiohttp` or in `python`.
