### ISSUE TITLE
IP is not in the Geo-database cause 500

### ISSUE THREAD

**Issue by GalAster** [vijos/vj4#232]
When you visit ```[www]/home/security``` with the IP which did not exist in the Geo-database, then you will get a 500 Internal Server Error.

This also happened on when you try to click "安全设置".

```html
500 Internal Server Error

Traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_protocol.py", line 422, in start
    resp = yield from self._request_handler(request)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web.py", line 306, in _handle
    resp = yield from handler(request)
  File "/home/[USERERNAME]/vj4/vj4/handler/base.py", line 219, in __iter__
    yield from super(Handler, self).__iter__()
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_urldispatcher.py", line 657, in __iter__
    resp = yield from method()
  File "/home/[USERERNAME]/vj4/vj4/handler/home.py", line 48, in get
    } for session in sessions)
  File "/home/[USERERNAME]/vj4/vj4/handler/home.py", line 48, in <genexpr>
    } for session in sessions)
  File "/home/[USERERNAME]/vj4/vj4/util/geoip.py", line 24, in ip2geo
    geodoc = _reader.city(ip)
  File "/usr/local/lib/python3.5/dist-packages/geoip2/database.py", line 110, in city
    return self._model_for(geoip2.models.City, 'City', ip_address)
  File "/usr/local/lib/python3.5/dist-packages/geoip2/database.py", line 191, in _model_for
    record = self._get(types, ip_address)
  File "/usr/local/lib/python3.5/dist-packages/geoip2/database.py", line 187, in _get
    "The address %s is not in the database." % ip_address)
geoip2.errors.AddressNotFoundError: The address 127.0.0.1 is not in the database.

```

Although a local visit is impossible, but there must be some other IPs don't in the Geo-database.

**Comment by breeswish** [comment]
Should be fixed in https://github.com/vijos/vj4/commit/e4bbefe6e6d2569e2dc4bac5117dd16bdb7da560 already.

**Comment by GalAster** [comment]
Well, that's all right...
Daily update is quite important...
