### ISSUE TITLE
请教npm run build的问题

### ISSUE THREAD

**Issue by Ruanxingzhi** [vijos/vj4#3]
系统 Ubuntu 15.10
node V4.4.4
RabbitMQ
MongoDB
python3.5  

问题开始在**npm run build**：

```
ERROR in ./pages/judge_playground.page.js

/home/blue/视频/vijos/vj4/ui/pages/judge_playground.page.js
  20:11  error  Parsing error: Unexpected token ..

✖ 1 problem (1 error, 0 warnings)


ERROR in ./components/discussion/comments.page.js

/home/blue/视频/vijos/vj4/ui/components/discussion/comments.page.js
  18:5  error  Parsing error: Unexpected token ..

✖ 1 problem (1 error, 0 warnings)


ERROR in ./components/discussion/CommentBox.js

/home/blue/视频/vijos/vj4/ui/components/discussion/CommentBox.js
  77:7  error  Parsing error: Unexpected token ..

✖ 1 problem (1 error, 0 warnings)


ERROR in ./misc/Util.js

/home/blue/视频/vijos/vj4/ui/misc/Util.js
  4:5  error  Parsing error: Unexpected token ..

✖ 1 problem (1 error, 0 warnings)


ERROR in ./components/DOMAttachedObject.js

/home/blue/视频/vijos/vj4/ui/components/DOMAttachedObject.js
  3:26  error  Parsing error: Unexpected token =

✖ 1 problem (1 error, 0 warnings)


ERROR in ./components/popup/Popup.js

/home/blue/视频/vijos/vj4/ui/components/popup/Popup.js
  6:28  error  Parsing error: Unexpected token =

✖ 1 problem (1 error, 0 warnings)

```

另外，python3.5 -m vj4.server --debug的时候也出现问题：

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/base_events.py", line 639, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/lib/python3.5/asyncio/futures.py", line 385, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 288, in _wakeup
    value = future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 436, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 5672)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/blue/视频/vijos/vj4/server.py", line 12, in <module>
    web.run_app(app.Application(),
  File "/home/blue/视频/vijos/vj4/app.py", line 40, in __init__
    self.loop.run_until_complete(asyncio.gather(tools.ensure_all_indexes(), bus.init()))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 343, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 237, in _step
    result = coro.throw(exc)
  File "/home/blue/视频/vijos/vj4/model/bus.py", line 12, in init
    channel = await _consume()
  File "/home/blue/视频/vijos/vj4/model/bus.py", line 16, in _consume
    channel = await mq.channel('bus')
  File "/home/blue/视频/vijos/vj4/mq.py", line 40, in channel
    channel = await (await _connect()).channel()
  File "/home/blue/视频/vijos/vj4/mq.py", line 18, in _connect
    virtualhost=options.options.mq_vhost)
  File "/home/blue/.local/lib/python3.5/site-packages/aioamqp/__init__.py", line 59, in connect
    factory, host, port, **create_connection_kwargs
  File "/usr/lib/python3.5/asyncio/base_events.py", line 661, in create_connection
    ', '.join(str(exc) for exc in exceptions)))
OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 5672, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5672)
```

请问如何解决？

**Comment by iceboy-sjtu** [comment]
I haven't encountered the npm build problem. It seems that some JS compiler or linter is complaining about the "..." syntax. For example in `judge_playground.page.js` line 20:

```js
19        const data = {
20          ...packet,
21          key,
22          tag: msg.tag,
23        };
```

Maybe you could upgrade your node modules? @SummerWish wrote these weird JSes.

Port 5672 should be listened by RabbitMQ. You probably didn't start the RabbitMQ server.

**Comment by iceboy-sjtu** [comment]
Closing issue since @Ruanxingzhi claims resolved in #4.

**Comment by laosb** [comment]
ES6 syntax are not so weird I think :wink:

**Comment by iceboy-sjtu** [comment]
@laosb JS is weird. ES6 was trying to make it better.

**Comment by laosb** [comment]
Ah I see.
