### ISSUE TITLE
RabbitMQ Errors: Waiter already exists

### ISSUE THREAD

**Issue by twd2** [vijos/vj4#374]
```
Oct 28 15:11:49 vj4 python3[1280]: #033[31m[E 171028 15:11:49 base:245]#033[0m System error by /p/1304/submit *.*.*.* *: SynchronizationError('Waiter already exists',)#033[0m
Oct 28 15:11:49 vj4 python3[1280]: #033[31m[E 171028 15:11:49 web_protocol:362]#033[0m Error handling request
Oct 28 15:11:49 vj4 python3[1280]: Traceback (most recent call last):
Oct 28 15:11:49 vj4 python3[1280]:   File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_protocol.py", line 422, in start
Oct 28 15:11:49 vj4 python3[1280]:     resp = yield from self._request_handler(request)
Oct 28 15:11:49 vj4 python3[1280]:   File "/usr/local/lib/python3.5/dist-packages/aiohttp/web.py", line 306, in _handle
Oct 28 15:11:49 vj4 python3[1280]:     resp = yield from handler(request)
Oct 28 15:11:49 vj4 python3[1280]:   File "/home/vijos/vj4/vj4/handler/base.py", line 226, in __iter__
Oct 28 15:11:49 vj4 python3[1280]:     yield from super(Handler, self).__iter__()
Oct 28 15:11:49 vj4 python3[1280]:   File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_urldispatcher.py", line 657, in __iter__
Oct 28 15:11:49 vj4 python3[1280]:     resp = yield from method()
Oct 28 15:11:49 vj4 python3[1280]:   File "/home/vijos/vj4/vj4/handler/base.py", line 443, in wrapped
Oct 28 15:11:49 vj4 python3[1280]:     return await coro(self, **kwargs, **await self.request.post())
Oct 28 15:11:49 vj4 python3[1280]:   File "/home/vijos/vj4/vj4/handler/problem.py", line 255, in post
Oct 28 15:11:49 vj4 python3[1280]:     self.user['_id'], lang, code)
Oct 28 15:11:49 vj4 python3[1280]:   File "/home/vijos/vj4/vj4/model/record.py", line 46, in add
Oct 28 15:11:49 vj4 python3[1280]:     await asyncio.gather(*post_coros)
Oct 28 15:11:49 vj4 python3[1280]:   File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
Oct 28 15:11:49 vj4 python3[1280]:     yield self  # This tells Task to wait for completion.
Oct 28 15:11:49 vj4 python3[1280]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
Oct 28 15:11:49 vj4 python3[1280]:     future.result()
Oct 28 15:11:49 vj4 python3[1280]:   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
Oct 28 15:11:49 vj4 python3[1280]:     raise self._exception
Oct 28 15:11:49 vj4 python3[1280]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
Oct 28 15:11:49 vj4 python3[1280]:     result = coro.send(None)
Oct 28 15:11:49 vj4 python3[1280]:   File "/home/vijos/vj4/vj4/service/queue.py", line 11, in publish
Oct 28 15:11:49 vj4 python3[1280]:     await channel.queue_declare(key)
Oct 28 15:11:49 vj4 python3[1280]:   File "/usr/local/lib/python3.5/dist-packages/aioamqp/channel.py", line 358, in queue_declare
Oct 28 15:11:49 vj4 python3[1280]:     'queue_declare', frame, request, no_wait))
Oct 28 15:11:49 vj4 python3[1280]:   File "/usr/local/lib/python3.5/dist-packages/aioamqp/channel.py", line 124, in _write_frame_awaiting_response
Oct 28 15:11:49 vj4 python3[1280]:     f = self._set_waiter(waiter_id)
Oct 28 15:11:49 vj4 python3[1280]:   File "/usr/local/lib/python3.5/dist-packages/aioamqp/channel.py", line 40, in _set_waiter
Oct 28 15:11:49 vj4 python3[1280]:     raise exceptions.SynchronizationError("Waiter already exists")
Oct 28 15:11:49 vj4 python3[1280]: aioamqp.exceptions.SynchronizationError: Waiter already exists#033[0m
```

**Comment by twd2** [comment]
What's this?
