### ISSUE TITLE
Unexpected HTTP 500 when domain not found

### ISSUE THREAD

**Issue by samhjn** [vijos/vj4#406]
When visiting
http://vijos.org/d/{{a_domain_name_has_not_registered_yet}}/
Vijos generated an HTTP 500 Error, which is expected to be HTTP 404.

**Comment by iceb0y** [comment]
```
Apr 17 16:00:56 vj4 vj4[14098] server.py E Error handling request
Traceback (most recent call last):
  File "/home/vijos/vj4/vj4/handler/base.py", line 223, in __iter__
    yield from HandlerBase.prepare(self)
  File "/home/vijos/vj4/vj4/handler/base.py", line 42, in prepare
    user.get_by_uid(uid), domain.get(self.domain_id), domain.get_user(self.domain_id, uid))
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/vijos/vj4/vj4/model/domain.py", line 66, in get
    raise error.DomainNotFoundError(domain_id)
vj4.error.DomainNotFoundError: viJOS

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_protocol.py", line 416, in start
    resp = yield from self._request_handler(request)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web.py", line 323, in _handle
    resp = yield from handler(request)
  File "/home/vijos/vj4/vj4/handler/base.py", line 238, in __iter__
    path_components=self.build_path((self.translate('error'), None)))
AttributeError: 'ProblemMainHandler' object has no attribute 'build_path'
```

**Comment by iceb0y** [comment]
```
diff --git a/vj4/handler/base.py b/vj4/handler/base.py
index e8b8da0..ed3a0dd 100644
--- a/vj4/handler/base.py
+++ b/vj4/handler/base.py
@@ -37,6 +37,10 @@ class HandlerBase(setting.SettingMixin):
     self.translate = locale.get_translate(options.default_locale)  # Default translate for errors.
     self.session = await self.update_session()
     self.domain_id = self.request.match_info.pop('domain_id', builtin.DOMAIN_ID_SYSTEM)
+    self.domain = builtin.DOMAIN_SYSTEM
+    self.user = builtin.USER_GUEST
+    self.domain_user = builtin.DOMAIN_USER_GUEST
+    self.timezone = None
     if 'uid' in self.session:
       uid = self.session['uid']
       self.user, self.domain, self.domain_user, bdoc = await asyncio.gather(
@@ -47,27 +51,21 @@ class HandlerBase(setting.SettingMixin):
       if not self.domain_user:
         self.domain_user = {}
     else:
-      self.user = builtin.USER_GUEST
       self.domain, bdoc = await asyncio.gather(
           domain.get(self.domain_id), blacklist.get(self.remote_ip))
       self.domain_user = builtin.DOMAIN_USER_GUEST
     self.view_lang = self.get_setting('view_lang')
-    # TODO(iceboy): UnknownTimeZoneError
-    self.timezone = pytz.timezone(self.get_setting('timezone'))
+    try:
+      self.timezone = pytz.timezone(self.get_setting('timezone'))
+    except pytz.exceptions.UnknownTimeZoneError:
+      pass
     self.translate = locale.get_translate(self.view_lang)
-    self.datetime_span = functools.partial(_datetime_span, timezone=self.timezone)
     self.datetime_stamp = _datetime_stamp
     if not self.domain:
       not_found_domain_id = self.domain_id
       self.domain_id = builtin.DOMAIN_ID_SYSTEM
       self.domain = builtin.DOMAIN_SYSTEM
-      self.reverse_url = functools.partial(_reverse_url, domain_id=self.domain_id)
-      self.build_path = functools.partial(_build_path, domain_id=self.domain_id,
-                                          domain_name=self.domain['name'])
       raise error.DomainNotFoundError(not_found_domain_id)
-    self.reverse_url = functools.partial(_reverse_url, domain_id=self.domain_id)
-    self.build_path = functools.partial(_build_path, domain_id=self.domain_id,
-                                        domain_name=self.domain['name'])
     if bdoc:
       raise error.BlacklistedError(self.remote_ip)
     if not self.GLOBAL and not self.has_priv(builtin.PRIV_VIEW_ALL_DOMAIN):
@@ -108,6 +106,16 @@ class HandlerBase(setting.SettingMixin):
   def own(self, doc, perm=builtin.PERM_NONE, field='owner_uid', priv=builtin.PRIV_NONE):
     return (doc[field] == self.user['_id']) and self.has_perm(perm) and self.has_priv(priv)
 
+  def reverse_url(self, name, **kwargs):
+    kwargs.setdefault('domain_id', self.domain_id)
+    return _reverse_url(name, **kwargs)
+
+  def build_path(self, *args):
+    return _build_path(*args, domain_id=self.domain_id, domain_name=self.domain['name'])
+
+  def datetime_span(self, dt, **kwargs):
+    return _datetime_span(dt, timezone=self.timezone, **kwargs)
+
   async def update_session(self, *, new_saved=False, **kwargs):
     """Update or create session if necessary.
 
diff --git a/vj4/server.py b/vj4/server.py
index 52dfc34..6e4139a 100644
--- a/vj4/server.py
+++ b/vj4/server.py
@@ -31,6 +31,7 @@ def main():
   else:
     syslog.enable_system_logging(level=logging.DEBUG if options.debug else logging.INFO,
                                  fmt='vj4[%(process)d] %(programname)s %(levelname).1s %(message)s')
   logging.getLogger('aioamqp').setLevel(logging.WARNING)
   logging.getLogger('sockjs').setLevel(logging.WARNING)
   url = urllib.parse.urlparse(options.listen)
   if url.scheme == 'http':
```

This fixes the problem but it's not ideal.
