### ISSUE TITLE
Bad SMTP address

### ISSUE THREAD

**Issue by iceb0y** [vijos/vj4#411]
```
Apr 17 15:37:32 vj4 vj4[14098] server.py E Exception in message handler.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sockjs/session.py", line 198, in _remote_message
    yield from self.handler(SockjsMessage(MSG_MESSAGE, msg), self)
  File "/home/vijos/vj4/vj4/app.py", line 97, in handler
    await session.on_message(**json.decode(msg.data))
  File "/home/vijos/vj4/vj4/handler/judge.py", line 191, in on_message
    await _post_judge(self, rdoc)
  File "/home/vijos/vj4/vj4/handler/judge.py", line 63, in _post_judge
    await asyncio.gather(*post_coros)
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/vijos/vj4/vj4/handler/judge.py", line 38, in _send_ac_mail
    'ac_mail.html', rdoc=rdoc, pdoc=pdoc, _=translate)
  File "/home/vijos/vj4/vj4/handler/base.py", line 215, in send_mail
    await mailer.send_mail(mail, '{0} - Vijos'.format(translate(title)), content)
  File "/home/vijos/vj4/vj4/service/mailer.py", line 24, in send_mail
    await server.sendmail(options.mail_from, to, msg.as_string())
  File "/usr/local/lib/python3.5/dist-packages/aiosmtplib/smtp.py", line 441, in sendmail
    raise SMTPRecipientsRefused(recipient_errors)
aiosmtplib.errors.SMTPRecipientsRefused: [SMTPRecipientRefused(501, 'Bad address syntax', '')]
```

**Comment by twd2** [comment]
Should be fixed by #448
