### ISSUE TITLE
npm run build failed

### ISSUE THREAD

**Issue by qwganker** [vijos/vj4#419]
wqiu@dell:~/work/cqrd/codecampus/vj4[dev]$ npm run build

> vj4@4.0.0 build /home/wqiu/work/cqrd/codecampus/vj4
> node scripts/build

(node:22226) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/home/wqiu/work/cqrd/codecampus/vj4/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/home/wqiu/work/cqrd/codecampus/vj4/node_modules/undertaker/lib/task.js:13:8)
    at exports.default (/home/wqiu/work/cqrd/codecampus/vj4/scripts/build/config/gulp.js:91:8)
    at _callee$ (/home/wqiu/work/cqrd/codecampus/vj4/scripts/build/runGulp.js:15:3)
    at tryCatch (/home/wqiu/work/cqrd/codecampus/vj4/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/wqiu/work/cqrd/codecampus/vj4/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/home/wqiu/work/cqrd/codecampus/vj4/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/wqiu/work/cqrd/codecampus/vj4/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/wqiu/work/cqrd/codecampus/vj4/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/home/wqiu/work/cqrd/codecampus/vj4/node_modules/core-js/library/modules/_export.js:35:28)
    at /home/wqiu/work/cqrd/codecampus/vj4/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at /home/wqiu/work/cqrd/codecampus/vj4/scripts/build/runGulp.js:88:17
    at _callee$ (/home/wqiu/work/cqrd/codecampus/vj4/scripts/build/main.js:9:9)
    at tryCatch (/home/wqiu/work/cqrd/codecampus/vj4/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/wqiu/work/cqrd/codecampus/vj4/node_modules/regenerator-runtime/runtime.js:303:22)
(node:22226) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22226) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by twd2** [comment]
Try nodejs 8.5, please.

**Comment by qwganker** [comment]
It's OK

**Comment by twd2** [comment]
Closing, if you have any further question, feel free to reopen this issue. :)
