### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by iceb0y** [vijos/vj4#439]
```
  File "/home/vj4/git/vj4/vj4/handler/base.py", line 227, in __await__
    yield from HandlerBase.prepare(self).__await__()
  File "/home/vj4/git/vj4/vj4/handler/base.py", line 52, in prepare
    domain.get(self.domain_id), blacklist.get(self.remote_ip))
  File "/home/vj4/opt/pypy3.5-6.0.0-linux_x86_64-portable/lib-python/3/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/home/vj4/opt/pypy3.5-6.0.0-linux_x86_64-portable/lib-python/3/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/home/vj4/opt/pypy3.5-6.0.0-linux_x86_64-portable/lib-python/3/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/home/vj4/opt/pypy3.5-6.0.0-linux_x86_64-portable/lib-python/3/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/vj4/git/vj4/vj4/model/domain.py", line 66, in get
    raise error.DomainNotFoundError(domain_id)
vj4.error.DomainNotFoundError: nnu.contest

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vj4/opt/pypy3.5-6.0.0-linux_x86_64-portable/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/home/vj4/opt/pypy3.5-6.0.0-linux_x86_64-portable/site-packages/aiohttp/web_app.py", line 366, in _handle
    resp = await handler(request)
  File "/home/vj4/git/vj4/vj4/handler/base.py", line 242, in __await__
    path_components=self.build_path((self.translate('error'), None)))
AttributeError: 'DomainMainHandler' object has no attribute 'build_path'
```

**Comment by iceb0y** [comment]
We need two step bootstrap for `domain`, `user`, `domain_user` and `timezone`. We already did this for `translate`, `session` and `domain_id`. Also need to restructure and deoptimize the code a little bit and benchmark with latest libraries and interpreters (both CPython and PyPy).

**Comment by twd2** [comment]
(known bug？)
