### ISSUE TITLE
#436 is not fully tested.

### ISSUE THREAD

**Issue by twd2** [vijos/vj4#443]
#436 is not fully tested.

**Comment by iceb0y** [comment]
That's ok if you mean CI since we don't have CI coverage for this area.

However we found more errors:

```
server.py E Error handling request
Traceback (most recent call last):
  File "/home/vj4/.local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/home/vj4/.local/lib/python3.6/site-packages/aiohttp/web_app.py", line 366, in _handle
    resp = await handler(request)
  File "/home/vj4/git/vj4/vj4/handler/base.py", line 228, in __await__
    yield from super(Handler, self).__await__()
  File "/home/vj4/.local/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 740, in _iter
    resp = await method()
  File "/home/vj4/git/vj4/vj4/handler/contest.py", line 334, in get
    tdoc, rows, udict = await self.get_scoreboard(tid)
  File "/home/vj4/git/vj4/vj4/handler/contest.py", line 96, in get_scoreboard
    ranked_tsdocs, udict, dudict, pdict)
  File "/home/vj4/git/vj4/vj4/model/adaptor/contest.py", line 152, in _acm_scoreboard
    'value': dudict[tsdoc['uid']]['display_name'] if 'display_name' in dudict[tsdoc['uid']] else ''})
KeyError: 134826

server.py E Error handling request
Traceback (most recent call last):
  File "/home/vj4/.local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/home/vj4/.local/lib/python3.6/site-packages/aiohttp/web_app.py", line 366, in _handle
    resp = await handler(request)
  File "/home/vj4/git/vj4/vj4/handler/base.py", line 228, in __await__
    yield from super(Handler, self).__await__()
  File "/home/vj4/.local/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 740, in _iter
    resp = await method()
  File "/home/vj4/git/vj4/vj4/handler/user.py", line 225, in get
    ddocs=ddocs, dcount=dcount, vndict=vndict)
  File "/home/vj4/git/vj4/vj4/handler/base.py", line 255, in render
    self.response.text = self.render_html(template_name, **kwargs)
  File "/home/vj4/git/vj4/vj4/handler/base.py", line 204, in render_html
    return template.Environment().get_template(template_name).render(kwargs)
  File "/home/vj4/.local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/vj4/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/vj4/.local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vj4/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/vj4/git/vj4/vj4/ui/templates/user_detail.html", line 2, in top-level template code
    {% extends "layout/basic.html" %}
  File "/home/vj4/git/vj4/vj4/ui/templates/layout/basic.html", line 2, in top-level template code
    {% extends "layout/html5.html" %}
  File "/home/vj4/git/vj4/vj4/ui/templates/layout/html5.html", line 36, in top-level template code
    {% block body %}{% endblock %}
  File "/home/vj4/git/vj4/vj4/ui/templates/layout/basic.html", line 12, in block "body"
    {% block content %}{% endblock %}
  File "/home/vj4/git/vj4/vj4/ui/templates/user_detail.html", line 15, in block "content"
    <p>
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by moesoha** [comment]
Seems there is no domain_user document in this case?

**Comment by twd2** [comment]
Please note that some users may not have their own dudoc in some domains.

**Comment by moesoha** [comment]
Create a dudoc for user who doesn't have one?On Dec 16, 2018 5:23 PM, Wende Tan <notifications@github.com> wrote:Please be aware that there are lots of points using dudoc !!!

**Comment by twd2** [comment]
I think we can create some dummies when needed. ^\_^ T\_T

**Comment by moesoha** [comment]
Like returning an empty dict when a user doesn't have a doc in the domain?On Dec 16, 2018 5:39 PM, Wende Tan <notifications@github.com> wrote:I think we can create some dummies when needed. ^_^ T_T

**Comment by moesoha** [comment]
![image](https://user-images.githubusercontent.com/5895757/50054883-19b24300-0182-11e9-825f-e02a28307e0c.png)

What about... Check every usage of `dudoc`/`dudict`? There are just 200 occurrences. *(JUST?????)*

**Comment by iceb0y** [comment]
Using `dudict` in jinja2 templates without checking is fine - the templates are using a different semantics for `[]`:

1. Any dict `d` with key `k` that does not exist in `d` has `d[k] = undefined`
2. Any key `k` has: `undefined[k] = undefined`
3. In production mode, undefined will be displayed as empty (i.e. `str(undefined) = ''`); In debug mode (with `--debug`) trying to display an undefined yields an error

(This is implemented in `vj4/template.py`.)

So in template code it's valid to check `d[a][b][c]`, and we only need to check `d[a]`, `d[a][b]` in python code. This should make the change needed much smaller.

**Comment by moesoha** [comment]
Exciting!

I'll fix that after lunch.
