### ISSUE TITLE
Got 500 after submit email when registering

### ISSUE THREAD

**Issue by moesoha** [vijos/vj4#444]
![image](https://user-images.githubusercontent.com/5895757/50071391-8ffb8780-020c-11e9-8399-f9152af9f091.png)

**Comment by moesoha** [comment]
That seems to not a problem of the server.

But it's better to tell user that we cannot send an email to this email address.

**Comment by twd2** [comment]
Catching more kinds of exceptions here should be helpful:

https://github.com/vijos/vj4/blob/0ad22079c6dfc30d210f9cb1f2c73fcab12dc54a/vj4/service/mailer.py#L31

**Comment by twd2** [comment]
Log:

```
Dec 17 14:59:36 vj4wz001 vj4[1090] server.py E Error handling request#012Traceback (most recent call last):#012  File "/home/vj4/.local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 390, in start#012    resp = await self._request_handler(request)#012  File "/home/vj4/.local/lib/python3.6/site-packages/aiohttp/web_app.py", line 366, in _handle#012    resp = await handler(request)#012  File "/home/vj4/git/vj4/vj4/handler/base.py", line 228, in __await__#012    yield from super(Handler, self).__await__()#012  File "/home/vj4/.local/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 740, in _iter#012    resp = await method()#012  File "/home/vj4/git/vj4/vj4/handler/base.py", line 453, in wrapped#012    return await coro(self, **kwargs, **await self.request.post())#012  File "/home/vj4/git/vj4/vj4/handler/base.py", line 496, in wrapped#012    return await coro(self, **kwargs)#012  File "/home/vj4/git/vj4/vj4/handler/user.py", line 57, in post#012    url=self.reverse_url('user_register_with_code', code=rid))#012  File "/home/vj4/git/vj4/vj4/handler/base.py", line 220, in send_mail#012    await mailer.send_mail(mail, '{0} - Vijos'.format(translate(title)), content)#012  File "/home/vj4/git/vj4/vj4/service/mailer.py", line 30, in send_mail#012    await server.sendmail(options.mail_from, to, msg.as_string())#012  File "/home/vj4/.local/lib/python3.6/site-packages/aiosmtplib/smtp.py", line 441, in sendmail#012    raise SMTPRecipientsRefused(recipient_errors)#012aiosmtplib.errors.SMTPRecipientsRefused: [SMTPRecipientRefused(550, 'Mailbox not found or access denied', '****@****.info')]
```
