### ISSUE TITLE
Server error during setting domain permission

### ISSUE THREAD

**Issue by iceb0y** [vijos/vj4#453]
```
server.py E System error by /d/ybttg/domain/permission redacted 117202: TypeError("post() got multiple values for keyword argument 'admin'",)
server.py E Error handling request
Traceback (most recent call last):
  File "/home/vj4/.local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 406, in start
    resp = await task
  File "/home/vj4/.local/lib/python3.6/site-packages/aiohttp/web_app.py", line 435, in _handle
    resp = await handler(request)
  File "/home/vj4/git/vj4/vj4/handler/base.py", line 228, in __await__
    yield from super(Handler, self).__await__()
  File "/home/vj4/.local/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 870, in _iter
    resp = await method()
  File "/home/vj4/git/vj4/vj4/handler/base.py", line 453, in wrapped
    return await coro(self, **kwargs, **await self.request.post())
TypeError: post() got multiple values for keyword argument 'admin'
```

**Comment by twd2** [comment]
Duplicated with #405, closing.
