### ISSUE TITLE
Custom test causes error

### ISSUE THREAD

**Issue by twd2** [vijos/vj4#479]
... when more than 2 test cases.

```
[E 190307 11:28:40 base:252] System error by /p/1000/pretest 10.1.1.198 -1: TypeError("post() got multiple values for keyword argument 'data_input'",)
[E 190307 11:28:40 web_protocol:355] Error handling request
Traceback (most recent call last):
  File "/Users/huzhiwei/Projects/zhixinfuture/vj4/.env/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/Users/huzhiwei/Projects/zhixinfuture/vj4/.env/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/Users/huzhiwei/Projects/zhixinfuture/vj4/vj4/handler/base.py", line 233, in __await__
    yield from super(Handler, self).__await__()
  File "/Users/huzhiwei/Projects/zhixinfuture/vj4/.env/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 890, in _iter
    resp = await method()
  File "/Users/huzhiwei/Projects/zhixinfuture/vj4/vj4/handler/base.py", line 453, in wrapped
    return await coro(self, **kwargs, **await self.request.post())
TypeError: post() got multiple values for keyword argument 'data_input'
```

might be related to #405

**Comment by twd2** [comment]
https://github.com/vijos/vj4/blob/master/vj4/handler/domain.py#L278
https://github.com/vijos/vj4/blob/master/vj4/handler/domain.py#L344
https://github.com/vijos/vj4/blob/master/vj4/handler/problem.py#L287
