### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by kevin50406418** [vijos/vj4#54]
When I use `python3.5 -m vj4.server` or `python3.5 -OO -m vj4.server --listen=unix:/var/run/vj4.sock`, it will return some error to me.

```
[I 160818 21:14:50 server:21] Server listening on http://127.0.0.1:8888
[I 160818 21:14:50 tools:17] Ensuring indexes for "document".
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vj4/vj4/vj4/server.py", line 50, in <module>
    sys.exit(main())
  File "/home/vj4/vj4/vj4/server.py", line 45, in main
    loop.run_until_complete(loop.create_server(app.Application().make_handler(), sock=sock))
  File "/home/vj4/vj4/vj4/app.py", line 47, in __init__
    self.loop.run_until_complete(asyncio.gather(tools.ensure_all_indexes(), bus.init()))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/vj4/vj4/vj4/service/bus.py", line 15, in init
    channel = await _consume()
  File "/home/vj4/vj4/vj4/service/bus.py", line 20, in _consume
    channel = await mq.channel('bus')
  File "/home/vj4/vj4/vj4/mq.py", line 45, in channel
    channel = await (await _connect()).channel()
  File "/home/vj4/vj4/vj4/mq.py", line 21, in _connect
    virtualhost=options.options.mq_vhost)
  File "/usr/local/lib/python3.5/dist-packages/aioamqp/__init__.py", line 59, in connect
    factory, host, port, **create_connection_kwargs
  File "/usr/lib/python3.5/asyncio/base_events.py", line 695, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.5/asyncio/base_events.py", line 682, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 402, in sock_connect
    return (yield from fut)
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 432, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 5672)

```

How to resolve the problem? Thank for your help.

**Comment by twd2** [comment]
It looks like you need to run rabbitmq server.

Thanks for trying vj4.
